### ISSUE TITLE
This thing randomly stops working all the time for me

### ISSUE THREAD

**Issue by jordanbleu** [midouest/vscode-playdate-debug#23] opened 2023-02-28 02:32 UTC
It works perfectly fine, but once in a while I'll go click the 'debug file in playdate simulator" and nothing happens at all.  Any tips on fixing that?  Re-installing doesn't seem to fix the issue, nor does restarting.  I'm on MacOS, VSCode v1.69.0.  I can build and run the file just fine in the PlayDate SDK CLI.

**Comment by midouest** [comment] 2023-02-28 03:26
Thanks for reporting this! I'm not sure what's happening based on your description, and unfortunately I have not been able to reproduce this (VSCode 1.75.1, macOS Ventura 13.2.1, Playdate SDK 1.13.1).

I have a few more questions:

- What Playdate SDK version are you using?
- If you quit the simulator when this happens, does it work the next time you hit "Debug file in Playdate Simulator"?
- Does it happen if you use "Run file in Playdate Simulator" instead of "Debug"?
- Are you stopping the previously running debugger before you click "Debug file in Playdate Simulator" again?

You could trying using the `tasks.json` and `launch.json` from the [basic configuration example](https://github.com/midouest/vscode-playdate-debug#tasks-and-debug-launcher) instead of using the "Debug file in Playdate Simulator" button. That button is intended to help you get up and running quickly, but I would expect the dedicated task/launch configuration to be a bit more stable.

**Comment by midouest** [comment] 2023-02-28 03:30
Also, is there any logging information in the VSCode task console? You should see something like this:

```shell
 *  Executing task: Playdate: Build 

Compiling...
> "/Users/me/Developer/PlaydateSDK/bin/pdc" --main -sdkpath "/Users/me/Developer/PlaydateSDK" "/Users/me/Developer/MyGame/source/main.lua" "/Users/me/Developer/MyGame/main.pdx"
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: Playdate: Run 

Starting Playdate Simulator...
> /usr/bin/open -a "/Users/me/Developer/PlaydateSDK/bin/Playdate Simulator.app"
 *  Terminal will be reused by tasks, press any key to close it. 

```

**Comment by jordanbleu** [comment] 2023-02-28 13:13
* I'm on the latest Playdate SDK, 1.13.1
* I have been quitting the simulator, unfortunately still doesn't work
* Run does not work either
* I am stopping the debugger

I think i may have found a reliable fix though, it seems that if I attach my debugger to some other process it fixes the issue for some reason.

**Comment by midouest** [comment] 2023-04-21 11:16
Closing because I cannot reproduce this issue.

**Closed as completed by midouest** 2023-04-21 11:16 UTC
